### ISSUE TITLE
Where can the resulting AppImage be downloaded?

### ISSUE THREAD

**Issue by probonopd** [lokedhs/docker-maxima-client#1]
Where can the resulting AppImage be downloaded?

**Comment by lokedhs** [comment]
I've added a README file that describes how to copy the resulting file from the image.

Also note that if you don't want to build it yourself, you can download a recent version of the executable from here: https://loke.keybase.pub/climaxima-x86_64.AppImage

**Comment by probonopd** [comment]
Thank you. Would be good if https://loke.keybase.pub/climaxima-x86_64.AppImage could be mentioned in the README.
